/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import EndUser.Admin;
import EndUser.Student;
import EndUser.User;
import java.awt.CardLayout;
import java.awt.Color;
import java.net.URL;
import javax.swing.BorderFactory;
import javax.swing.JPanel;

/**
 *
 * @author Zeyad
 */
public class ChangePasswordPanel_P extends javax.swing.JPanel {
    protected User user ;
    private CardLayout cardLayout;
    private JPanel container;
    /**
     * Creates new form ChangeAdminPasswordp
     */
    public ChangePasswordPanel_P(User user, CardLayout cardLayout, JPanel container) {
        initComponents();
        WrongOldPassword.setVisible(false);
        WrongMatching.setVisible(false);
        WrongNewPassword.setVisible(false);
        Comfirmed.setVisible(false);
        if (user instanceof Admin) {
            this.user = (Admin) user ;
        }
        else if (user instanceof Student) {
            this.user = (Student) user ;
        }
        this.cardLayout = cardLayout;
        this.container = container;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel3 = new javax.swing.JLabel();
        ChangePagetitle = new javax.swing.JLabel();
        ComfirmButton = new javax.swing.JButton();
        OldPasswordField = new javax.swing.JTextField();
        WrongOldPassword = new javax.swing.JLabel();
        OldPassword = new javax.swing.JLabel();
        MatchingNewPasswordField = new javax.swing.JTextField();
        NewPasswordField = new javax.swing.JTextField();
        NewPassword = new javax.swing.JLabel();
        ReNewPassword = new javax.swing.JLabel();
        WrongNewPassword = new javax.swing.JLabel();
        WrongMatching = new javax.swing.JLabel();
        Comfirmed = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        lengthLabel = new javax.swing.JLabel();
        uppercaseLabel = new javax.swing.JLabel();
        lowercaseLabel = new javax.swing.JLabel();
        specialCharLabel = new javax.swing.JLabel();
        digitLabel = new javax.swing.JLabel();

        jLabel3.setText("jLabel2");

        setBackground(new java.awt.Color(244, 242, 226));
        setForeground(new java.awt.Color(244, 242, 226));
        setLayout(new java.awt.GridBagLayout());

        ChangePagetitle.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        ChangePagetitle.setForeground(new java.awt.Color(0, 0, 0));
        ChangePagetitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChangePagetitle.setText("Change Password Page");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 142;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(ChangePagetitle, gridBagConstraints);

        ComfirmButton.setBackground(new java.awt.Color(74, 25, 72));
        ComfirmButton.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        ComfirmButton.setText("Comfirm");
        ComfirmButton.setEnabled(false);
        ComfirmButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ComfirmButtonStateChanged(evt);
            }
        });
        ComfirmButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComfirmButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ComfirmButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ComfirmButtonMouseExited(evt);
            }
        });
        ComfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComfirmButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(ComfirmButton, gridBagConstraints);

        OldPasswordField.setBackground(new java.awt.Color(255, 255, 255));
        OldPasswordField.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        OldPasswordField.setForeground(new java.awt.Color(0, 0, 0));
        OldPasswordField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(74, 25, 72), 3, true));
        OldPasswordField.setPreferredSize(new java.awt.Dimension(200, 35));
        OldPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                OldPasswordFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                OldPasswordFieldKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 328;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(OldPasswordField, gridBagConstraints);

        WrongOldPassword.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        WrongOldPassword.setForeground(new java.awt.Color(220, 0, 0));
        WrongOldPassword.setText("Wrong Password. Please, try again");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(WrongOldPassword, gridBagConstraints);

        OldPassword.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        OldPassword.setForeground(new java.awt.Color(0, 0, 0));
        OldPassword.setText("Old Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(OldPassword, gridBagConstraints);

        MatchingNewPasswordField.setBackground(new java.awt.Color(255, 255, 255));
        MatchingNewPasswordField.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        MatchingNewPasswordField.setForeground(new java.awt.Color(0, 0, 0));
        MatchingNewPasswordField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(74, 25, 72), 3, true));
        MatchingNewPasswordField.setPreferredSize(new java.awt.Dimension(200, 35));
        MatchingNewPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MatchingNewPasswordFieldKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.ipadx = 328;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(MatchingNewPasswordField, gridBagConstraints);

        NewPasswordField.setBackground(new java.awt.Color(255, 255, 255));
        NewPasswordField.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        NewPasswordField.setForeground(new java.awt.Color(0, 0, 0));
        NewPasswordField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(74, 25, 72), 3, true));
        NewPasswordField.setPreferredSize(new java.awt.Dimension(200, 35));
        NewPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NewPasswordFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NewPasswordFieldKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.ipadx = 328;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(NewPasswordField, gridBagConstraints);

        NewPassword.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        NewPassword.setForeground(new java.awt.Color(0, 0, 0));
        NewPassword.setText("New Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(NewPassword, gridBagConstraints);

        ReNewPassword.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        ReNewPassword.setForeground(new java.awt.Color(0, 0, 0));
        ReNewPassword.setText("Rewrite New Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(ReNewPassword, gridBagConstraints);

        WrongNewPassword.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        WrongNewPassword.setForeground(new java.awt.Color(220, 0, 0));
        WrongNewPassword.setText("Wrong Password. Please follow the Required");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(WrongNewPassword, gridBagConstraints);

        WrongMatching.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        WrongMatching.setForeground(new java.awt.Color(220, 0, 0));
        WrongMatching.setText("The passwords do not match. Please check.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(WrongMatching, gridBagConstraints);

        Comfirmed.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        Comfirmed.setForeground(new java.awt.Color(0, 170, 0));
        Comfirmed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Comfirmed.setText("Password Changed Successfully ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 108;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(Comfirmed, gridBagConstraints);

        BackButton.setBackground(new java.awt.Color(74, 25, 72));
        BackButton.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        BackButton.setToolTipText("Click to go back");
        BackButton.setBorderPainted(false);
        BackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackButton.setFocusPainted(false);
        BackButton.setFocusable(false);
        BackButton.setMaximumSize(new java.awt.Dimension(145, 60));
        BackButton.setMinimumSize(new java.awt.Dimension(145, 60));
        BackButton.setPreferredSize(new java.awt.Dimension(145, 60));
        BackButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BackButtonFocusGained(evt);
            }
        });
        BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackButtonMouseExited(evt);
            }
        });
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(BackButton, gridBagConstraints);

        lengthLabel.setFont(new java.awt.Font("Consolas", 0, 20)); // NOI18N
        lengthLabel.setForeground(new java.awt.Color(0, 0, 0));
        lengthLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lengthLabel.setText("- 12-20 characters long");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 100);
        add(lengthLabel, gridBagConstraints);

        uppercaseLabel.setFont(new java.awt.Font("Consolas", 0, 20)); // NOI18N
        uppercaseLabel.setForeground(new java.awt.Color(0, 0, 0));
        uppercaseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uppercaseLabel.setText("- At least one uppercase letter ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(uppercaseLabel, gridBagConstraints);

        lowercaseLabel.setFont(new java.awt.Font("Consolas", 0, 20)); // NOI18N
        lowercaseLabel.setForeground(new java.awt.Color(0, 0, 0));
        lowercaseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lowercaseLabel.setText("- At least one lowercase letter");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 12);
        add(lowercaseLabel, gridBagConstraints);

        specialCharLabel.setFont(new java.awt.Font("Consolas", 0, 20)); // NOI18N
        specialCharLabel.setForeground(new java.awt.Color(0, 0, 0));
        specialCharLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        specialCharLabel.setText("- At least one special character");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(specialCharLabel, gridBagConstraints);

        digitLabel.setFont(new java.awt.Font("Consolas", 0, 20)); // NOI18N
        digitLabel.setForeground(new java.awt.Color(0, 0, 0));
        digitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        digitLabel.setText("- At least one digit");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 135);
        add(digitLabel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void ComfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComfirmButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComfirmButtonActionPerformed

    private void OldPasswordFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_OldPasswordFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_OldPasswordFieldKeyTyped

    private void NewPasswordFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NewPasswordFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_NewPasswordFieldKeyTyped

    private void MatchingNewPasswordFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MatchingNewPasswordFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_MatchingNewPasswordFieldKeyTyped

    private void ComfirmButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComfirmButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ComfirmButtonMouseClicked

    private void ComfirmButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComfirmButtonMouseEntered
        // TODO add your handling code here:
        ComfirmButton.setBackground(Color.decode("#F4F2E2"));
        ComfirmButton.setBorder(BorderFactory.createLineBorder(Color.BLACK, 5, true));
        ComfirmButton.setBorderPainted(true);
        ComfirmButton.setForeground(Color.BLACK);
    }//GEN-LAST:event_ComfirmButtonMouseEntered

    private void ComfirmButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComfirmButtonMouseExited
        // TODO add your handling code here:
        ComfirmButton.setBackground(Color.decode("#4A1948"));
        ComfirmButton.setBorderPainted(false);
        ComfirmButton.setForeground(Color.decode("#F4F2E2"));
    }//GEN-LAST:event_ComfirmButtonMouseExited

    private void BackButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BackButtonFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_BackButtonFocusGained

    private void BackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseClicked
        // TODO add your handling code here:
        
        /*cardLayout.show(container, "StudentMenu");*/
    }//GEN-LAST:event_BackButtonMouseClicked

    private void BackButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseEntered
        // TODO add your handling code here:
        URL iconURL = getClass().getResource("/lib/turn-back.png");
        if (iconURL != null) {
            BackButton.setIcon(new javax.swing.ImageIcon(iconURL));
        } else {
            // Handle the error, e.g., log it or show a default icon
            System.err.println("Resource not found: /lib/turn-back.png");
        }
        BackButton.setBackground(Color.decode("#F4F2E2"));
        BackButton.setBorder(BorderFactory.createLineBorder(Color.BLACK, 5, true));
        BackButton.setBorderPainted(true);
    }//GEN-LAST:event_BackButtonMouseEntered

    private void BackButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseExited
        // TODO add your handling code here:
        URL iconURL = getClass().getResource("/lib/turnback-40.png");
        if (iconURL != null) {
            BackButton.setIcon(new javax.swing.ImageIcon(iconURL));
        } else {
            // Handle the error, e.g., log it or show a default icon
            System.err.println("Resource not found: /lib/turnback-40.png");
        }
        BackButton.setBackground(Color.decode("#4A1948"));
        BackButton.setBorderPainted(false);
        BackButton.setForeground(Color.decode("#F4F2E2"));
    }//GEN-LAST:event_BackButtonMouseExited

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        Comfirmed.setVisible(false);
        WrongMatching.setVisible(false);
        WrongNewPassword.setVisible(false);
        WrongOldPassword.setVisible(false);
        cardLayout.show(container, "StudentMenu");
    }//GEN-LAST:event_BackButtonActionPerformed

    private void NewPasswordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NewPasswordFieldKeyReleased
        // TODO add your handling code here:
        checkPasswordRequirements(new String(NewPasswordField.getText()));
    }//GEN-LAST:event_NewPasswordFieldKeyReleased

    private void OldPasswordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_OldPasswordFieldKeyReleased
        // TODO add your handling code here:
        if (!user.verifyPassword(OldPasswordField.getText())){
            WrongOldPassword.setVisible(true);
        } else {
            WrongOldPassword.setVisible(false);
        }
    }//GEN-LAST:event_OldPasswordFieldKeyReleased

    private void ComfirmButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ComfirmButtonStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_ComfirmButtonStateChanged
public void checkPasswordRequirements(String password) {
        // Length check
        if (password.length() >= 12 && password.length() <= 20) {
            lengthLabel.setText("[√] Length is good");
            lengthLabel.setForeground(new Color(0, 150, 0));
        } else {
            lengthLabel.setText("[X] Must be 12-20 characters");
            lengthLabel.setForeground(Color.RED);
        }

        // Uppercase check
        if (password.matches(".*[A-Z].*")) {
            uppercaseLabel.setText("[√] Has uppercase");
            uppercaseLabel.setForeground(new Color(0, 150, 0));
        } else {
            uppercaseLabel.setText("[X] Need uppercase letter");
            uppercaseLabel.setForeground(Color.RED);
        }

        // Lowercase check
        if (password.matches(".*[a-z].*")) {
            lowercaseLabel.setText("[√] Has lowercase");
            lowercaseLabel.setForeground(new Color(0, 150, 0));
        } else {
            lowercaseLabel.setText("[X] Need lowercase letter");
            lowercaseLabel.setForeground(Color.RED);
        }

        // Special character check
        if (password.matches(".*[!@#$%^&*()_+\\-=\\[\\]{};':\"\\\\|,.<>/?].*")) {
            specialCharLabel.setText("[√] Has special character");
            specialCharLabel.setForeground(new Color(0, 150, 0));
        } else {
            specialCharLabel.setText("[X] Need special character");
            specialCharLabel.setForeground(Color.RED);
        }

        // Digit check
        if (password.matches(".*\\d.*")) {
            digitLabel.setText("[√] Has number");
            digitLabel.setForeground(new Color(0, 150, 0));
        } else {
            digitLabel.setText("[X] Need a number");
            digitLabel.setForeground(Color.RED);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel ChangePagetitle;
    private javax.swing.JButton ComfirmButton;
    private javax.swing.JLabel Comfirmed;
    private javax.swing.JTextField MatchingNewPasswordField;
    private javax.swing.JLabel NewPassword;
    private javax.swing.JTextField NewPasswordField;
    private javax.swing.JLabel OldPassword;
    private javax.swing.JTextField OldPasswordField;
    private javax.swing.JLabel ReNewPassword;
    private javax.swing.JLabel WrongMatching;
    private javax.swing.JLabel WrongNewPassword;
    private javax.swing.JLabel WrongOldPassword;
    private javax.swing.JLabel digitLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lengthLabel;
    private javax.swing.JLabel lowercaseLabel;
    private javax.swing.JLabel specialCharLabel;
    private javax.swing.JLabel uppercaseLabel;
    // End of variables declaration//GEN-END:variables
}

