/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author Zeyad
 */
public class UpdateStudentprofileP extends javax.swing.JPanel {

    /**
     * Creates new form UpdateStudentprofileP
     */
    public UpdateStudentprofileP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Backbutton = new javax.swing.JButton();
        UpdateStudentAddress = new javax.swing.JButton();
        UpdateStudentName = new javax.swing.JButton();
        UpdateStudentEmail = new javax.swing.JButton();
        UpdateStudentUsername = new javax.swing.JButton();
        UpdateStudentprofile = new javax.swing.JLabel();
        UpdateStudentInstitute = new javax.swing.JButton();

        setBackground(new java.awt.Color(244, 242, 226));

        Backbutton.setBackground(new java.awt.Color(0, 0, 0));
        Backbutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Zeyad\\myproject\\TestApp\\TestGeneratorSystem\\lib\\turnback-40.png")); // NOI18N
        Backbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackbuttonMouseClicked(evt);
            }
        });

        UpdateStudentAddress.setBackground(new java.awt.Color(74, 25, 72));
        UpdateStudentAddress.setText("Update Address");
        UpdateStudentAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateStudentAddressMouseClicked(evt);
            }
        });

        UpdateStudentName.setBackground(new java.awt.Color(74, 25, 72));
        UpdateStudentName.setText("Update Name");
        UpdateStudentName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateStudentNameMouseClicked(evt);
            }
        });

        UpdateStudentEmail.setBackground(new java.awt.Color(74, 25, 72));
        UpdateStudentEmail.setText("Update Email");
        UpdateStudentEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateStudentEmailMouseClicked(evt);
            }
        });

        UpdateStudentUsername.setBackground(new java.awt.Color(74, 25, 72));
        UpdateStudentUsername.setText("Update Username");
        UpdateStudentUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateStudentUsernameMouseClicked(evt);
            }
        });

        UpdateStudentprofile.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        UpdateStudentprofile.setForeground(new java.awt.Color(0, 0, 0));
        UpdateStudentprofile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UpdateStudentprofile.setText("Update Profile");

        UpdateStudentInstitute.setBackground(new java.awt.Color(74, 25, 72));
        UpdateStudentInstitute.setText("Institute");
        UpdateStudentInstitute.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateStudentInstituteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UpdateStudentUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UpdateStudentEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UpdateStudentName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UpdateStudentAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UpdateStudentprofile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(UpdateStudentInstitute, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UpdateStudentprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UpdateStudentUsername)
                .addGap(18, 18, 18)
                .addComponent(UpdateStudentEmail)
                .addGap(18, 18, 18)
                .addComponent(UpdateStudentName)
                .addGap(18, 18, 18)
                .addComponent(UpdateStudentAddress)
                .addGap(18, 18, 18)
                .addComponent(UpdateStudentInstitute)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 55, Short.MAX_VALUE)
                .addComponent(Backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackbuttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BackbuttonMouseClicked

    private void UpdateStudentAddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateStudentAddressMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateStudentAddressMouseClicked

    private void UpdateStudentNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateStudentNameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateStudentNameMouseClicked

    private void UpdateStudentEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateStudentEmailMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateStudentEmailMouseClicked

    private void UpdateStudentUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateStudentUsernameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateStudentUsernameMouseClicked

    private void UpdateStudentInstituteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateStudentInstituteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateStudentInstituteMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbutton;
    private javax.swing.JButton UpdateStudentAddress;
    private javax.swing.JButton UpdateStudentEmail;
    private javax.swing.JButton UpdateStudentInstitute;
    private javax.swing.JButton UpdateStudentName;
    private javax.swing.JButton UpdateStudentUsername;
    private javax.swing.JLabel UpdateStudentprofile;
    // End of variables declaration//GEN-END:variables
}
