/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author Zeyad
 */
public class ViewProfilePanelAdminP extends javax.swing.JPanel {

    /**
     * Creates new form ViewProfilePanelP
     */
    public ViewProfilePanelAdminP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Username = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        FirstName = new javax.swing.JLabel();
        LastName = new javax.swing.JLabel();
        Department = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        JoinDate = new javax.swing.JLabel();
        ContactNumber = new javax.swing.JLabel();
        Backbutton = new javax.swing.JButton();
        AdminJoinDateField = new javax.swing.JTextField();
        AdminContactNumField = new javax.swing.JTextField();
        AdminDepartmentField = new javax.swing.JTextField();
        AdminAddressField = new javax.swing.JTextField();
        AdminLnameField = new javax.swing.JTextField();
        AdminFnameField = new javax.swing.JTextField();
        AdminEmailField = new javax.swing.JTextField();
        AdminUsernameField = new javax.swing.JTextField();
        AdminProfLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(244, 242, 226));
        setForeground(new java.awt.Color(74, 25, 72));

        Username.setBackground(new java.awt.Color(74, 25, 72));
        Username.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        Username.setForeground(new java.awt.Color(0, 0, 0));
        Username.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Username.setText("Username");

        Email.setBackground(new java.awt.Color(74, 25, 72));
        Email.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        Email.setForeground(new java.awt.Color(0, 0, 0));
        Email.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Email.setText("Email");

        FirstName.setBackground(new java.awt.Color(74, 25, 72));
        FirstName.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        FirstName.setForeground(new java.awt.Color(0, 0, 0));
        FirstName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        FirstName.setText("First Name");

        LastName.setBackground(new java.awt.Color(74, 25, 72));
        LastName.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        LastName.setForeground(new java.awt.Color(0, 0, 0));
        LastName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LastName.setText("Last Name");

        Department.setBackground(new java.awt.Color(74, 25, 72));
        Department.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        Department.setForeground(new java.awt.Color(0, 0, 0));
        Department.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Department.setText("Department");

        Address.setBackground(new java.awt.Color(74, 25, 72));
        Address.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        Address.setForeground(new java.awt.Color(0, 0, 0));
        Address.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Address.setText("Address");

        JoinDate.setBackground(new java.awt.Color(74, 25, 72));
        JoinDate.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        JoinDate.setForeground(new java.awt.Color(0, 0, 0));
        JoinDate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JoinDate.setText("Join Date");

        ContactNumber.setBackground(new java.awt.Color(74, 25, 72));
        ContactNumber.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        ContactNumber.setForeground(new java.awt.Color(0, 0, 0));
        ContactNumber.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ContactNumber.setText("Contact Number");

        Backbutton.setBackground(new java.awt.Color(0, 0, 0));
        Backbutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Zeyad\\myproject\\TestApp\\TestGeneratorSystem\\lib\\turnback-40.png")); // NOI18N
        Backbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackbuttonMouseClicked(evt);
            }
        });

        AdminJoinDateField.setEditable(false);
        AdminJoinDateField.setBackground(new java.awt.Color(255, 255, 255));
        AdminJoinDateField.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        AdminJoinDateField.setForeground(new java.awt.Color(0, 0, 0));
        AdminJoinDateField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 3, true));
        AdminJoinDateField.setCaretColor(new java.awt.Color(0, 0, 0));
        AdminJoinDateField.setSelectionColor(new java.awt.Color(51, 0, 51));

        AdminContactNumField.setEditable(false);
        AdminContactNumField.setBackground(new java.awt.Color(255, 255, 255));
        AdminContactNumField.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        AdminContactNumField.setForeground(new java.awt.Color(0, 0, 0));
        AdminContactNumField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 3, true));
        AdminContactNumField.setSelectionColor(new java.awt.Color(51, 0, 51));

        AdminDepartmentField.setEditable(false);
        AdminDepartmentField.setBackground(new java.awt.Color(255, 255, 255));
        AdminDepartmentField.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        AdminDepartmentField.setForeground(new java.awt.Color(0, 0, 0));
        AdminDepartmentField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 3, true));
        AdminDepartmentField.setSelectionColor(new java.awt.Color(51, 0, 51));
        AdminDepartmentField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminDepartmentFieldActionPerformed(evt);
            }
        });

        AdminAddressField.setEditable(false);
        AdminAddressField.setBackground(new java.awt.Color(255, 255, 255));
        AdminAddressField.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        AdminAddressField.setForeground(new java.awt.Color(0, 0, 0));
        AdminAddressField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 3, true));
        AdminAddressField.setSelectionColor(new java.awt.Color(51, 0, 51));
        AdminAddressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminAddressFieldActionPerformed(evt);
            }
        });

        AdminLnameField.setEditable(false);
        AdminLnameField.setBackground(new java.awt.Color(255, 255, 255));
        AdminLnameField.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        AdminLnameField.setForeground(new java.awt.Color(0, 0, 0));
        AdminLnameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 3, true));
        AdminLnameField.setSelectionColor(new java.awt.Color(51, 0, 51));

        AdminFnameField.setEditable(false);
        AdminFnameField.setBackground(new java.awt.Color(255, 255, 255));
        AdminFnameField.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        AdminFnameField.setForeground(new java.awt.Color(0, 0, 0));
        AdminFnameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 3, true));
        AdminFnameField.setSelectionColor(new java.awt.Color(51, 0, 51));

        AdminEmailField.setEditable(false);
        AdminEmailField.setBackground(new java.awt.Color(255, 255, 255));
        AdminEmailField.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        AdminEmailField.setForeground(new java.awt.Color(0, 0, 0));
        AdminEmailField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 3, true));
        AdminEmailField.setSelectionColor(new java.awt.Color(51, 0, 51));

        AdminUsernameField.setEditable(false);
        AdminUsernameField.setBackground(new java.awt.Color(255, 255, 255));
        AdminUsernameField.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        AdminUsernameField.setForeground(new java.awt.Color(0, 0, 0));
        AdminUsernameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 3, true));
        AdminUsernameField.setSelectionColor(new java.awt.Color(51, 0, 51));

        AdminProfLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        AdminProfLabel.setForeground(new java.awt.Color(0, 0, 0));
        AdminProfLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdminProfLabel.setText("Admin Profile");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminProfLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(ContactNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(AdminContactNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(Department, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AdminDepartmentField, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(AdminEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AdminUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(AdminAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(AdminLnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(AdminFnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JoinDate, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AdminJoinDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdminProfLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AdminUsernameField, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(Username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AdminEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(Email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AdminFnameField, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(FirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminLnameField, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Department, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminDepartmentField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(ContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AdminContactNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JoinDate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminJoinDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(Backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AdminDepartmentFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminDepartmentFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminDepartmentFieldActionPerformed

    private void AdminAddressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminAddressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminAddressFieldActionPerformed

    private void BackbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackbuttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BackbuttonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JTextField AdminAddressField;
    private javax.swing.JTextField AdminContactNumField;
    private javax.swing.JTextField AdminDepartmentField;
    private javax.swing.JTextField AdminEmailField;
    private javax.swing.JTextField AdminFnameField;
    private javax.swing.JTextField AdminJoinDateField;
    private javax.swing.JTextField AdminLnameField;
    private javax.swing.JLabel AdminProfLabel;
    private javax.swing.JTextField AdminUsernameField;
    private javax.swing.JButton Backbutton;
    private javax.swing.JLabel ContactNumber;
    private javax.swing.JLabel Department;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel FirstName;
    private javax.swing.JLabel JoinDate;
    private javax.swing.JLabel LastName;
    private javax.swing.JLabel Username;
    // End of variables declaration//GEN-END:variables
}
