/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author Zeyad
 */
public class ViewProfilePanelStudentP extends javax.swing.JPanel {

    /**
     * Creates new form ViewProfilePanelStudentP
     */
    public ViewProfilePanelStudentP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Username = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Fname = new javax.swing.JLabel();
        Lname = new javax.swing.JLabel();
        Grade = new javax.swing.JLabel();
        StudentPassedTC = new javax.swing.JLabel();
        Institute = new javax.swing.JLabel();
        StudentTotalTOT = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        StudentTakenTestsArea = new javax.swing.JTextArea();
        BackButton = new javax.swing.JButton();
        StudentUsernameField = new javax.swing.JTextField();
        StudentEmailField = new javax.swing.JTextField();
        StudentFnameField = new javax.swing.JTextField();
        StudentAddressField = new javax.swing.JTextField();
        StudentInstituteField = new javax.swing.JTextField();
        StudentGradeField = new javax.swing.JTextField();
        StudentLnameField = new javax.swing.JTextField();
        StudentPassedTCField = new javax.swing.JTextField();
        StudentMenu = new javax.swing.JLabel();
        StudentTotalTOTField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(244, 242, 226));
        setForeground(new java.awt.Color(244, 242, 226));

        Username.setBackground(new java.awt.Color(74, 25, 72));
        Username.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        Username.setForeground(new java.awt.Color(74, 25, 72));
        Username.setText("Username");

        Address.setBackground(new java.awt.Color(74, 25, 72));
        Address.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        Address.setForeground(new java.awt.Color(74, 25, 72));
        Address.setText("Address");

        Email.setBackground(new java.awt.Color(74, 25, 72));
        Email.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        Email.setForeground(new java.awt.Color(74, 25, 72));
        Email.setText("Email");

        Fname.setBackground(new java.awt.Color(74, 25, 72));
        Fname.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        Fname.setForeground(new java.awt.Color(74, 25, 72));
        Fname.setText("First Name");

        Lname.setBackground(new java.awt.Color(74, 25, 72));
        Lname.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        Lname.setForeground(new java.awt.Color(74, 25, 72));
        Lname.setText("Last Name");

        Grade.setBackground(new java.awt.Color(74, 25, 72));
        Grade.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        Grade.setForeground(new java.awt.Color(74, 25, 72));
        Grade.setText("Grade");

        StudentPassedTC.setBackground(new java.awt.Color(74, 25, 72));
        StudentPassedTC.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        StudentPassedTC.setForeground(new java.awt.Color(74, 25, 72));
        StudentPassedTC.setText("Passed Tests Count");

        Institute.setBackground(new java.awt.Color(74, 25, 72));
        Institute.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        Institute.setForeground(new java.awt.Color(74, 25, 72));
        Institute.setText("Institute");

        StudentTotalTOT.setBackground(new java.awt.Color(74, 25, 72));
        StudentTotalTOT.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        StudentTotalTOT.setForeground(new java.awt.Color(74, 25, 72));
        StudentTotalTOT.setText("Total Time Of All Tests");

        jLabel10.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(74, 25, 72));
        jLabel10.setText("Taken Tests:");

        StudentTakenTestsArea.setEditable(false);
        StudentTakenTestsArea.setBackground(new java.awt.Color(74, 25, 72));
        StudentTakenTestsArea.setColumns(20);
        StudentTakenTestsArea.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        StudentTakenTestsArea.setRows(5);
        jScrollPane1.setViewportView(StudentTakenTestsArea);

        BackButton.setBackground(new java.awt.Color(0, 0, 0));
        BackButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Zeyad\\myproject\\TestApp\\TestGeneratorSystem\\lib\\turnback-40.png")); // NOI18N
        BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButtonMouseClicked(evt);
            }
        });

        StudentUsernameField.setEditable(false);
        StudentUsernameField.setBackground(new java.awt.Color(74, 25, 72));
        StudentUsernameField.setForeground(new java.awt.Color(244, 242, 226));

        StudentEmailField.setEditable(false);
        StudentEmailField.setBackground(new java.awt.Color(74, 25, 72));

        StudentFnameField.setEditable(false);
        StudentFnameField.setBackground(new java.awt.Color(74, 25, 72));
        StudentFnameField.setForeground(new java.awt.Color(244, 242, 226));

        StudentAddressField.setEditable(false);
        StudentAddressField.setBackground(new java.awt.Color(74, 25, 72));
        StudentAddressField.setForeground(new java.awt.Color(244, 242, 226));

        StudentInstituteField.setEditable(false);
        StudentInstituteField.setBackground(new java.awt.Color(74, 25, 72));
        StudentInstituteField.setForeground(new java.awt.Color(244, 242, 226));

        StudentGradeField.setEditable(false);
        StudentGradeField.setBackground(new java.awt.Color(74, 25, 72));

        StudentLnameField.setEditable(false);
        StudentLnameField.setBackground(new java.awt.Color(74, 25, 72));
        StudentLnameField.setForeground(new java.awt.Color(244, 242, 226));

        StudentPassedTCField.setEditable(false);
        StudentPassedTCField.setBackground(new java.awt.Color(74, 25, 72));
        StudentPassedTCField.setForeground(new java.awt.Color(244, 242, 226));

        StudentMenu.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        StudentMenu.setForeground(new java.awt.Color(0, 0, 0));
        StudentMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StudentMenu.setText("Student Menu");
        StudentMenu.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        StudentTotalTOTField.setEditable(false);
        StudentTotalTOTField.setBackground(new java.awt.Color(74, 25, 72));
        StudentTotalTOTField.setForeground(new java.awt.Color(244, 242, 226));
        StudentTotalTOTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentTotalTOTFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Lname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Fname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Grade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Institute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(StudentPassedTC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(StudentTotalTOT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(StudentUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(StudentPassedTCField)
                        .addComponent(StudentInstituteField)
                        .addComponent(StudentGradeField)
                        .addComponent(StudentFnameField)
                        .addComponent(StudentEmailField)
                        .addComponent(StudentLnameField)
                        .addComponent(StudentAddressField)
                        .addComponent(StudentTotalTOTField, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StudentMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(StudentMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(StudentUsernameField)
                    .addComponent(Username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(StudentEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(StudentFnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(StudentLnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(StudentAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(StudentGradeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Grade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(StudentInstituteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Institute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(StudentPassedTCField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StudentPassedTC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(StudentTotalTOTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StudentTotalTOT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BackButtonMouseClicked

    private void StudentTotalTOTFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentTotalTOTFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentTotalTOTFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Fname;
    private javax.swing.JLabel Grade;
    private javax.swing.JLabel Institute;
    private javax.swing.JLabel Lname;
    private javax.swing.JTextField StudentAddressField;
    private javax.swing.JTextField StudentEmailField;
    private javax.swing.JTextField StudentFnameField;
    private javax.swing.JTextField StudentGradeField;
    private javax.swing.JTextField StudentInstituteField;
    private javax.swing.JTextField StudentLnameField;
    private javax.swing.JLabel StudentMenu;
    private javax.swing.JLabel StudentPassedTC;
    private javax.swing.JTextField StudentPassedTCField;
    private javax.swing.JTextArea StudentTakenTestsArea;
    private javax.swing.JLabel StudentTotalTOT;
    private javax.swing.JTextField StudentTotalTOTField;
    private javax.swing.JTextField StudentUsernameField;
    private javax.swing.JLabel Username;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
