package GUI.AdminPanels;

import EndUser.Admin;
import GUI.ChangePasswordPanel_P;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Zeyad
 */
public class AdminDashboardMenuP extends javax.swing.JPanel {

    private CardLayout cardLayout;
    private JPanel container;
    protected Admin admin;
    ViewProfilePanelAdminP VAdmin;
    ChangePasswordPanel_P ChangePass;
    UpdateAdminprofileP UpdateAdminProf;
    ModifyCategoryPanel1 modifyCategoryPanel1;
    CreateCategoryPanel createCategoryPanel;
    DeleteCategoryPanel deleteCategoryPanel;
    DeleteQuestionPanel1 deleteQuestionPanel1;
    AddQuestionPanel1 addQuestionPanel1;
    UpdateQuestionPanel1 updateQuestionPanel1;

    /**
     * Creates new form AdminDashboardMenuP
     *
     * @param admin
     * @param cardLayout
     * @param container
     */
    public AdminDashboardMenuP(Admin admin, CardLayout cardLayout, JPanel container) {
        this.admin = admin;
        this.cardLayout = cardLayout;
        this.container = container;
        initComponents();
        VAdmin = new ViewProfilePanelAdminP(admin, cardLayout, container);
        ChangePass = new ChangePasswordPanel_P(admin, cardLayout, container);
        UpdateAdminProf = new UpdateAdminprofileP(admin, cardLayout, container);
        // waiting kareem create Panels
        modifyCategoryPanel1 = new ModifyCategoryPanel1(cardLayout, container, admin);
        createCategoryPanel = new CreateCategoryPanel(cardLayout, container, admin);
        deleteCategoryPanel = new DeleteCategoryPanel(cardLayout, container, admin);
        deleteQuestionPanel1 = new DeleteQuestionPanel1(cardLayout, container, admin);
        addQuestionPanel1 = new AddQuestionPanel1(cardLayout, container, admin);
        updateQuestionPanel1 = new UpdateQuestionPanel1(cardLayout, container, admin);
        container.add(updateQuestionPanel1, "updateQuestion1");
        container.add(addQuestionPanel1, "addQuestion1");
        container.add(deleteQuestionPanel1, "deleteQuestion1");
        container.add(deleteCategoryPanel, "deleteCategory");
        container.add(createCategoryPanel, "createCategory");
        container.add(modifyCategoryPanel1, "modifyCategory1");
        container.add(VAdmin, "AdminViewProf");
        container.add(ChangePass, "AdminChangePass");
        container.add(UpdateAdminProf, "AdminUpdateprof");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jDialog1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton10 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        AdminMenu = new javax.swing.JLabel();
        ViewProfile = new javax.swing.JButton();
        UpdateProfile = new javax.swing.JButton();
        CreateCategory = new javax.swing.JButton();
        ChangePassword = new javax.swing.JButton();
        DeleteAccount = new javax.swing.JButton();
        ModifyCategory = new javax.swing.JButton();
        DeleteCategory = new javax.swing.JButton();
        AddQuestion = new javax.swing.JButton();
        UpdateQuestion = new javax.swing.JButton();
        DeleteQuestion = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jTextPane1);

        jButton10.setBackground(new java.awt.Color(74, 25, 72));
        jButton10.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        jButton10.setForeground(new java.awt.Color(244, 242, 226));
        jButton10.setText("Login");
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.setFocusPainted(false);
        jButton10.setPreferredSize(new java.awt.Dimension(145, 60));
        jButton10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton10MouseMoved(evt);
            }
        });
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton10MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton10MousePressed(evt);
            }
        });
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton23.setBackground(new java.awt.Color(74, 25, 72));
        jButton23.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        jButton23.setForeground(new java.awt.Color(244, 242, 226));
        jButton23.setText("Login");
        jButton23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton23.setFocusPainted(false);
        jButton23.setPreferredSize(new java.awt.Dimension(145, 60));
        jButton23.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton23MouseMoved(evt);
            }
        });
        jButton23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton23MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton23MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton23MousePressed(evt);
            }
        });
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        jButton26.setBackground(new java.awt.Color(74, 25, 72));
        jButton26.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        jButton26.setForeground(new java.awt.Color(244, 242, 226));
        jButton26.setText("Login");
        jButton26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton26.setFocusPainted(false);
        jButton26.setPreferredSize(new java.awt.Dimension(145, 60));
        jButton26.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton26MouseMoved(evt);
            }
        });
        jButton26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton26MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton26MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton26MousePressed(evt);
            }
        });
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(255, 250, 206));
        setToolTipText("");
        setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        setLayout(new java.awt.GridBagLayout());

        Logout.setBackground(new java.awt.Color(0, 0, 0));
        Logout.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 0, 0));
        Logout.setText("Logout");
        Logout.setBorderPainted(false);
        Logout.setFocusPainted(false);
        Logout.setFocusable(false);
        Logout.setMaximumSize(new java.awt.Dimension(100, 100));
        Logout.setMinimumSize(new java.awt.Dimension(50, 40));
        Logout.setPreferredSize(new java.awt.Dimension(150, 40));
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutMouseExited(evt);
            }
        });
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        add(Logout, gridBagConstraints);

        AdminMenu.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        AdminMenu.setForeground(new java.awt.Color(0, 0, 0));
        AdminMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdminMenu.setText("Admin Menu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 343;
        gridBagConstraints.insets = new java.awt.Insets(19, 6, 0, 10);
        add(AdminMenu, gridBagConstraints);

        ViewProfile.setBackground(new java.awt.Color(74, 25, 72));
        ViewProfile.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        ViewProfile.setForeground(new java.awt.Color(244, 242, 226));
        ViewProfile.setText("View Profile");
        ViewProfile.setBorderPainted(false);
        ViewProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewProfile.setFocusPainted(false);
        ViewProfile.setFocusable(false);
        ViewProfile.setPreferredSize(new java.awt.Dimension(145, 80));
        ViewProfile.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ViewProfileMouseMoved(evt);
            }
        });
        ViewProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ViewProfileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ViewProfileMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ViewProfileMousePressed(evt);
            }
        });
        ViewProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewProfileActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 201;
        gridBagConstraints.ipady = -25;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(ViewProfile, gridBagConstraints);

        UpdateProfile.setBackground(new java.awt.Color(74, 25, 72));
        UpdateProfile.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        UpdateProfile.setForeground(new java.awt.Color(244, 242, 226));
        UpdateProfile.setText("Update Profile");
        UpdateProfile.setBorderPainted(false);
        UpdateProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UpdateProfile.setFocusPainted(false);
        UpdateProfile.setFocusable(false);
        UpdateProfile.setPreferredSize(new java.awt.Dimension(145, 80));
        UpdateProfile.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                UpdateProfileMouseMoved(evt);
            }
        });
        UpdateProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UpdateProfileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UpdateProfileMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UpdateProfileMousePressed(evt);
            }
        });
        UpdateProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateProfileActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.ipady = -25;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(UpdateProfile, gridBagConstraints);

        CreateCategory.setBackground(new java.awt.Color(74, 25, 72));
        CreateCategory.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        CreateCategory.setForeground(new java.awt.Color(244, 242, 226));
        CreateCategory.setText("Create Category");
        CreateCategory.setBorderPainted(false);
        CreateCategory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CreateCategory.setFocusPainted(false);
        CreateCategory.setFocusable(false);
        CreateCategory.setPreferredSize(new java.awt.Dimension(145, 80));
        CreateCategory.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                CreateCategoryMouseMoved(evt);
            }
        });
        CreateCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateCategoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CreateCategoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CreateCategoryMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CreateCategoryMousePressed(evt);
            }
        });
        CreateCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateCategoryActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.ipady = -25;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(CreateCategory, gridBagConstraints);

        ChangePassword.setBackground(new java.awt.Color(74, 25, 72));
        ChangePassword.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        ChangePassword.setForeground(new java.awt.Color(244, 242, 226));
        ChangePassword.setText("Change Password");
        ChangePassword.setBorderPainted(false);
        ChangePassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ChangePassword.setFocusPainted(false);
        ChangePassword.setFocusable(false);
        ChangePassword.setPreferredSize(new java.awt.Dimension(145, 80));
        ChangePassword.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ChangePasswordMouseMoved(evt);
            }
        });
        ChangePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ChangePasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ChangePasswordMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ChangePasswordMousePressed(evt);
            }
        });
        ChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePasswordActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.ipady = -25;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(ChangePassword, gridBagConstraints);

        DeleteAccount.setBackground(new java.awt.Color(74, 25, 72));
        DeleteAccount.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        DeleteAccount.setForeground(new java.awt.Color(244, 242, 226));
        DeleteAccount.setText("Delete Account");
        DeleteAccount.setBorderPainted(false);
        DeleteAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeleteAccount.setFocusPainted(false);
        DeleteAccount.setFocusable(false);
        DeleteAccount.setPreferredSize(new java.awt.Dimension(145, 80));
        DeleteAccount.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                DeleteAccountMouseMoved(evt);
            }
        });
        DeleteAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DeleteAccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DeleteAccountMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DeleteAccountMousePressed(evt);
            }
        });
        DeleteAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteAccountActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.ipady = -25;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(DeleteAccount, gridBagConstraints);

        ModifyCategory.setBackground(new java.awt.Color(74, 25, 72));
        ModifyCategory.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        ModifyCategory.setForeground(new java.awt.Color(244, 242, 226));
        ModifyCategory.setText("Modify Category");
        ModifyCategory.setBorderPainted(false);
        ModifyCategory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ModifyCategory.setFocusPainted(false);
        ModifyCategory.setFocusable(false);
        ModifyCategory.setPreferredSize(new java.awt.Dimension(145, 80));
        ModifyCategory.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ModifyCategoryMouseMoved(evt);
            }
        });
        ModifyCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ModifyCategoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ModifyCategoryMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ModifyCategoryMousePressed(evt);
            }
        });
        ModifyCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyCategoryActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.ipady = -25;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(ModifyCategory, gridBagConstraints);

        DeleteCategory.setBackground(new java.awt.Color(74, 25, 72));
        DeleteCategory.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        DeleteCategory.setForeground(new java.awt.Color(244, 242, 226));
        DeleteCategory.setText("Delete Category");
        DeleteCategory.setBorderPainted(false);
        DeleteCategory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeleteCategory.setFocusPainted(false);
        DeleteCategory.setFocusable(false);
        DeleteCategory.setPreferredSize(new java.awt.Dimension(145, 80));
        DeleteCategory.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                DeleteCategoryMouseMoved(evt);
            }
        });
        DeleteCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteCategoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DeleteCategoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DeleteCategoryMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DeleteCategoryMousePressed(evt);
            }
        });
        DeleteCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteCategoryActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.ipady = -25;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(DeleteCategory, gridBagConstraints);

        AddQuestion.setBackground(new java.awt.Color(74, 25, 72));
        AddQuestion.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        AddQuestion.setForeground(new java.awt.Color(244, 242, 226));
        AddQuestion.setText("Add Question");
        AddQuestion.setBorderPainted(false);
        AddQuestion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddQuestion.setFocusPainted(false);
        AddQuestion.setFocusable(false);
        AddQuestion.setPreferredSize(new java.awt.Dimension(145, 80));
        AddQuestion.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                AddQuestionMouseMoved(evt);
            }
        });
        AddQuestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddQuestionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddQuestionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddQuestionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AddQuestionMousePressed(evt);
            }
        });
        AddQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddQuestionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.ipady = -25;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(AddQuestion, gridBagConstraints);

        UpdateQuestion.setBackground(new java.awt.Color(74, 25, 72));
        UpdateQuestion.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        UpdateQuestion.setForeground(new java.awt.Color(244, 242, 226));
        UpdateQuestion.setText("Update Question");
        UpdateQuestion.setBorderPainted(false);
        UpdateQuestion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UpdateQuestion.setFocusPainted(false);
        UpdateQuestion.setFocusable(false);
        UpdateQuestion.setPreferredSize(new java.awt.Dimension(145, 80));
        UpdateQuestion.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                UpdateQuestionMouseMoved(evt);
            }
        });
        UpdateQuestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateQuestionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UpdateQuestionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UpdateQuestionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UpdateQuestionMousePressed(evt);
            }
        });
        UpdateQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateQuestionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.ipady = -25;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(UpdateQuestion, gridBagConstraints);

        DeleteQuestion.setBackground(new java.awt.Color(74, 25, 72));
        DeleteQuestion.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        DeleteQuestion.setForeground(new java.awt.Color(244, 242, 226));
        DeleteQuestion.setText("Delete Question");
        DeleteQuestion.setBorderPainted(false);
        DeleteQuestion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeleteQuestion.setFocusPainted(false);
        DeleteQuestion.setFocusable(false);
        DeleteQuestion.setPreferredSize(new java.awt.Dimension(145, 80));
        DeleteQuestion.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                DeleteQuestionMouseMoved(evt);
            }
        });
        DeleteQuestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteQuestionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DeleteQuestionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DeleteQuestionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DeleteQuestionMousePressed(evt);
            }
        });
        DeleteQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteQuestionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.ipady = -25;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(DeleteQuestion, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        container.remove(VAdmin);
        container.remove(ChangePass);
        container.remove(UpdateAdminProf);
        container.remove(updateQuestionPanel1);
        container.remove(addQuestionPanel1);
        container.remove(deleteQuestionPanel1);
        container.remove(deleteCategoryPanel);
        container.remove(createCategoryPanel);
        container.remove(modifyCategoryPanel1);
        container.revalidate();
        container.repaint();
        VAdmin = null;
        ChangePass = null;
        UpdateAdminProf = null;
        modifyCategoryPanel1 = null;
        createCategoryPanel = null;
        deleteCategoryPanel = null;
        deleteQuestionPanel1 = null;
        addQuestionPanel1 = null;
        updateQuestionPanel1 = null;
        admin = new Admin();
        System.gc();
        cardLayout.show(container, "Welcome");
    }//GEN-LAST:event_LogoutActionPerformed

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutMouseClicked

    private void jButton10MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10MouseMoved

    private void jButton10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseEntered
        // TODO add your handling code here:
        /*jButton3.setBackground(Color.decode("#F4F2E2"));
        jButton3.setBorder(BorderFactory.createLineBorder(Color.BLACK, 5, true));
        jButton3.setBorderPainted(true);
        jButton3.setForeground(Color.BLACK);*/
    }//GEN-LAST:event_jButton10MouseEntered

    private void jButton10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseExited
        // TODO add your handling code here:
        /*jButton3.setBackground(Color.decode("#4A1948"));
        jButton3.setBorderPainted(false);
        jButton3.setForeground(Color.decode("#F4F2E2"));*/
    }//GEN-LAST:event_jButton10MouseExited

    private void jButton10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10MousePressed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

    }//GEN-LAST:event_jButton10ActionPerformed

    private void ViewProfileMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewProfileMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewProfileMouseMoved

    private void ViewProfileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewProfileMouseEntered
        // TODO add your handling code here:
        ViewProfile.setBackground(Color.decode("#F4F2E2"));
        ViewProfile.setBorder(BorderFactory.createLineBorder(Color.BLACK, 5, true));
        ViewProfile.setBorderPainted(true);
        ViewProfile.setForeground(Color.BLACK);
    }//GEN-LAST:event_ViewProfileMouseEntered

    private void ViewProfileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewProfileMouseExited
        // TODO add your handling code here:
        ViewProfile.setBackground(Color.decode("#4A1948"));
        ViewProfile.setBorderPainted(false);
        ViewProfile.setForeground(Color.decode("#F4F2E2"));
    }//GEN-LAST:event_ViewProfileMouseExited

    private void ViewProfileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewProfileMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewProfileMousePressed

    private void ViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewProfileActionPerformed
        // TODO add your handling code here:
        container.add(new ViewProfilePanelAdminP( admin, cardLayout, container), "AdminViewProf");
        cardLayout.show(container, "AdminViewProf");
    }//GEN-LAST:event_ViewProfileActionPerformed

    private void UpdateProfileMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateProfileMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateProfileMouseMoved

    private void UpdateProfileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateProfileMouseEntered
        // TODO add your handling code here:
        UpdateProfile.setBackground(Color.decode("#F4F2E2"));
        UpdateProfile.setBorder(BorderFactory.createLineBorder(Color.BLACK, 5, true));
        UpdateProfile.setBorderPainted(true);
        UpdateProfile.setForeground(Color.BLACK);
    }//GEN-LAST:event_UpdateProfileMouseEntered

    private void UpdateProfileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateProfileMouseExited
        // TODO add your handling code here:
        UpdateProfile.setBackground(Color.decode("#4A1948"));
        UpdateProfile.setBorderPainted(false);
        UpdateProfile.setForeground(Color.decode("#F4F2E2"));
    }//GEN-LAST:event_UpdateProfileMouseExited

    private void UpdateProfileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateProfileMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateProfileMousePressed

    private void UpdateProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateProfileActionPerformed
        // TODO add your handling code here:
        container.add(new UpdateQuestionPanel1(cardLayout, container, admin), "AdminUpdateprof");
        cardLayout.show(container, "AdminUpdateprof");
    }//GEN-LAST:event_UpdateProfileActionPerformed

    private void CreateCategoryMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateCategoryMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateCategoryMouseMoved

    private void CreateCategoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateCategoryMouseEntered
        // TODO add your handling code here:
        CreateCategory.setBackground(Color.decode("#F4F2E2"));
        CreateCategory.setBorder(BorderFactory.createLineBorder(Color.BLACK, 5, true));
        CreateCategory.setBorderPainted(true);
        CreateCategory.setForeground(Color.BLACK);
    }//GEN-LAST:event_CreateCategoryMouseEntered

    private void CreateCategoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateCategoryMouseExited
        // TODO add your handling code here:
        CreateCategory.setBackground(Color.decode("#4A1948"));
        CreateCategory.setBorderPainted(false);
        CreateCategory.setForeground(Color.decode("#F4F2E2"));
    }//GEN-LAST:event_CreateCategoryMouseExited

    private void CreateCategoryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateCategoryMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateCategoryMousePressed

    private void CreateCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateCategoryActionPerformed

    private void ChangePasswordMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePasswordMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_ChangePasswordMouseMoved

    private void ChangePasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePasswordMouseEntered
        // TODO add your handling code here:
        ChangePassword.setBackground(Color.decode("#F4F2E2"));
        ChangePassword.setBorder(BorderFactory.createLineBorder(Color.BLACK, 5, true));
        ChangePassword.setBorderPainted(true);
        ChangePassword.setForeground(Color.BLACK);
    }//GEN-LAST:event_ChangePasswordMouseEntered

    private void ChangePasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePasswordMouseExited
        // TODO add your handling code here:
        ChangePassword.setBackground(Color.decode("#4A1948"));
        ChangePassword.setBorderPainted(false);
        ChangePassword.setForeground(Color.decode("#F4F2E2"));
    }//GEN-LAST:event_ChangePasswordMouseExited

    private void ChangePasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePasswordMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChangePasswordMousePressed

    private void ChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePasswordActionPerformed
        // TODO add your handling code here:
        container.add(new ChangePasswordPanel_P(admin, cardLayout, container), "AdminChangePass");
        cardLayout.show(container, "AdminChangePass");
    }//GEN-LAST:event_ChangePasswordActionPerformed

    private void DeleteAccountMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteAccountMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteAccountMouseMoved

    private void DeleteAccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteAccountMouseEntered
        // TODO add your handling code here:
        DeleteAccount.setBackground(Color.decode("#F4F2E2"));
        DeleteAccount.setBorder(BorderFactory.createLineBorder(Color.BLACK, 5, true));
        DeleteAccount.setBorderPainted(true);
        DeleteAccount.setForeground(Color.BLACK);
    }//GEN-LAST:event_DeleteAccountMouseEntered

    private void DeleteAccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteAccountMouseExited
        // TODO add your handling code here:
        DeleteAccount.setBackground(Color.decode("#4A1948"));
        DeleteAccount.setBorderPainted(false);
        DeleteAccount.setForeground(Color.decode("#F4F2E2"));
    }//GEN-LAST:event_DeleteAccountMouseExited

    private void DeleteAccountMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteAccountMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteAccountMousePressed

    private void DeleteAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteAccountActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(
                null, // Parent component (null for center of screen)
                "Are you sure to delete the the account?", // Message
                "Delete Account alert", // Title
                JOptionPane.YES_NO_OPTION, // Options
                JOptionPane.QUESTION_MESSAGE // Icon type
        );
        if (response == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(
                    null,
                    "The Account Deleted!",
                    "The Account Deleted",
                    JOptionPane.INFORMATION_MESSAGE
            );
            admin.removeAccount();
            LogoutMouseClicked();
        } else {
            JOptionPane.showMessageDialog(
                    null,
                    "Delete is disabled",
                    "Delete is disabled",
                    JOptionPane.INFORMATION_MESSAGE
            );
        }
    }//GEN-LAST:event_DeleteAccountActionPerformed

    private void jButton23MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton23MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23MouseMoved

    private void jButton23MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton23MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23MouseEntered

    private void jButton23MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton23MouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton23MouseExited

    private void jButton23MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton23MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23MousePressed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23ActionPerformed

    private void ModifyCategoryMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifyCategoryMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_ModifyCategoryMouseMoved

    private void ModifyCategoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifyCategoryMouseEntered
        // TODO add your handling code here:
        ModifyCategory.setBackground(Color.decode("#F4F2E2"));
        ModifyCategory.setBorder(BorderFactory.createLineBorder(Color.BLACK, 5, true));
        ModifyCategory.setBorderPainted(true);
        ModifyCategory.setForeground(Color.BLACK);
    }//GEN-LAST:event_ModifyCategoryMouseEntered

    private void ModifyCategoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifyCategoryMouseExited
        // TODO add your handling code here:
        ModifyCategory.setBackground(Color.decode("#4A1948"));
        ModifyCategory.setBorderPainted(false);
        ModifyCategory.setForeground(Color.decode("#F4F2E2"));
    }//GEN-LAST:event_ModifyCategoryMouseExited

    private void ModifyCategoryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifyCategoryMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModifyCategoryMousePressed

    private void ModifyCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyCategoryActionPerformed
        // TODO add your handling code here:
        cardLayout.show(container, "modifyCategory1");
    }//GEN-LAST:event_ModifyCategoryActionPerformed

    private void DeleteCategoryMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteCategoryMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteCategoryMouseMoved

    private void DeleteCategoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteCategoryMouseEntered
        // TODO add your handling code here:
        DeleteCategory.setBackground(Color.decode("#F4F2E2"));
        DeleteCategory.setBorder(BorderFactory.createLineBorder(Color.BLACK, 5, true));
        DeleteCategory.setBorderPainted(true);
        DeleteCategory.setForeground(Color.BLACK);
    }//GEN-LAST:event_DeleteCategoryMouseEntered

    private void DeleteCategoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteCategoryMouseExited
        // TODO add your handling code here:
        DeleteCategory.setBackground(Color.decode("#4A1948"));
        DeleteCategory.setBorderPainted(false);
        DeleteCategory.setForeground(Color.decode("#F4F2E2"));
    }//GEN-LAST:event_DeleteCategoryMouseExited

    private void DeleteCategoryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteCategoryMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteCategoryMousePressed

    private void DeleteCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteCategoryActionPerformed

    private void jButton26MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton26MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton26MouseMoved

    private void jButton26MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton26MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton26MouseEntered

    private void jButton26MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton26MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton26MouseExited

    private void jButton26MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton26MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton26MousePressed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton26ActionPerformed

    private void AddQuestionMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddQuestionMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_AddQuestionMouseMoved

    private void AddQuestionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddQuestionMouseEntered
        // TODO add your handling code here:
        AddQuestion.setBackground(Color.decode("#F4F2E2"));
        AddQuestion.setBorder(BorderFactory.createLineBorder(Color.BLACK, 5, true));
        AddQuestion.setBorderPainted(true);
        AddQuestion.setForeground(Color.BLACK);
    }//GEN-LAST:event_AddQuestionMouseEntered

    private void AddQuestionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddQuestionMouseExited
        // TODO add your handling code here:
        AddQuestion.setBackground(Color.decode("#4A1948"));
        AddQuestion.setBorderPainted(false);
        AddQuestion.setForeground(Color.decode("#F4F2E2"));
    }//GEN-LAST:event_AddQuestionMouseExited

    private void AddQuestionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddQuestionMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddQuestionMousePressed

    private void AddQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddQuestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddQuestionActionPerformed

    private void UpdateQuestionMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateQuestionMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateQuestionMouseMoved

    private void UpdateQuestionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateQuestionMouseEntered
        // TODO add your handling code here:
        UpdateQuestion.setBackground(Color.decode("#F4F2E2"));
        UpdateQuestion.setBorder(BorderFactory.createLineBorder(Color.BLACK, 5, true));
        UpdateQuestion.setBorderPainted(true);
        UpdateQuestion.setForeground(Color.BLACK);
    }//GEN-LAST:event_UpdateQuestionMouseEntered

    private void UpdateQuestionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateQuestionMouseExited
        // TODO add your handling code here:
        UpdateQuestion.setBackground(Color.decode("#4A1948"));
        UpdateQuestion.setBorderPainted(false);
        UpdateQuestion.setForeground(Color.decode("#F4F2E2"));
    }//GEN-LAST:event_UpdateQuestionMouseExited

    private void UpdateQuestionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateQuestionMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateQuestionMousePressed

    private void UpdateQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateQuestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateQuestionActionPerformed

    private void DeleteQuestionMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteQuestionMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteQuestionMouseMoved

    private void DeleteQuestionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteQuestionMouseEntered
        // TODO add your handling code here:
        DeleteQuestion.setBackground(Color.decode("#F4F2E2"));
        DeleteQuestion.setBorder(BorderFactory.createLineBorder(Color.BLACK, 5, true));
        DeleteQuestion.setBorderPainted(true);
        DeleteQuestion.setForeground(Color.BLACK);
    }//GEN-LAST:event_DeleteQuestionMouseEntered

    private void DeleteQuestionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteQuestionMouseExited
        // TODO add your handling code here:
        DeleteQuestion.setBackground(Color.decode("#4A1948"));
        DeleteQuestion.setBorderPainted(false);
        DeleteQuestion.setForeground(Color.decode("#F4F2E2"));
    }//GEN-LAST:event_DeleteQuestionMouseExited

    private void DeleteQuestionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteQuestionMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteQuestionMousePressed

    private void DeleteQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteQuestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteQuestionActionPerformed

    private void LogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseEntered
        // TODO add your handling code here:
        Logout.setBackground(Color.decode("#F4F2E2"));
        Logout.setBorder(BorderFactory.createLineBorder(Color.BLACK, 5, true));
        Logout.setBorderPainted(true);
        Logout.setForeground(Color.BLACK);
    }//GEN-LAST:event_LogoutMouseEntered

    private void LogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseExited
        // TODO add your handling code here:
        Logout.setBackground(Color.decode("#000000"));
        Logout.setBorderPainted(false);
        Logout.setForeground(Color.decode("#FF0000"));
    }//GEN-LAST:event_LogoutMouseExited

    private void CreateCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateCategoryMouseClicked
        // TODO add your handling code here:
        cardLayout.show(container, "createCategory");
    }//GEN-LAST:event_CreateCategoryMouseClicked

    private void DeleteCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteCategoryMouseClicked
        // TODO add your handling code here:
        cardLayout.show(container, "deleteCategory");
    }//GEN-LAST:event_DeleteCategoryMouseClicked

    private void DeleteQuestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteQuestionMouseClicked
        // TODO add your handling code here:
        cardLayout.show(container, "deleteQuestion1");

    }//GEN-LAST:event_DeleteQuestionMouseClicked

    private void AddQuestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddQuestionMouseClicked
        // TODO add your handling code here:
        cardLayout.show(container, "addQuestion1");
    }//GEN-LAST:event_AddQuestionMouseClicked

    private void UpdateQuestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateQuestionMouseClicked
        // TODO add your handling code here:
        cardLayout.show(container, "updateQuestion1");
    }//GEN-LAST:event_UpdateQuestionMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddQuestion;
    private javax.swing.JLabel AdminMenu;
    private javax.swing.JButton ChangePassword;
    private javax.swing.JButton CreateCategory;
    private javax.swing.JButton DeleteAccount;
    private javax.swing.JButton DeleteCategory;
    private javax.swing.JButton DeleteQuestion;
    private javax.swing.JButton Logout;
    private javax.swing.JButton ModifyCategory;
    private javax.swing.JButton UpdateProfile;
    private javax.swing.JButton UpdateQuestion;
    private javax.swing.JButton ViewProfile;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton26;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

    private void LogoutMouseClicked() {
        container.remove(VAdmin);
        container.remove(ChangePass);
        container.remove(UpdateAdminProf);
        /*container.remove(UpdateAdminProf); 
        container.remove(UpdateAdminProf); 
        container.remove(UpdateAdminProf); 
        container.remove(UpdateAdminProf); 
        container.remove(UpdateAdminProf);*/
        container.revalidate();
        container.repaint();
        VAdmin = null;
        ChangePass = null;
        UpdateAdminProf = null;
        admin = new Admin();
        System.gc();
        cardLayout.show(container, "Welcome");
    }
}
