/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.StudentPanels;

import EndUser.Student;
import GUI.AdminPanels.ViewProfilePanelAdminP;
import GUI.ChangePasswordPanel_P;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Zeyad
 */
public class StudentDashboardMenuP extends javax.swing.JPanel {

    private Student student;
    private CardLayout cardLayout;
    private JPanel container;
    ChangePasswordPanel_P ChangePass ;
    ViewProfilePanelStudentPanelP VStudent ;
    UpdateStudentprofileP UpdateStudentProf ;
    ViewFavoriteQuestions FAVQuesView ;
    ViewTestHistoryPanelP TestHisView ;
    /*UpdateStudentprofileP UpdateStudentProf ; waiting Take Test*/
    private setUpTest setTest;

    /**
     * Creates new form StudentDashboardMenuP
     */
    public StudentDashboardMenuP(Student student, CardLayout cardLayout, JPanel container) {
        initComponents();
        this.student = student;
        this.cardLayout = cardLayout;
        this.container = container; 
        UpdateStudentProf = new UpdateStudentprofileP(student, cardLayout, container);
        VStudent = new ViewProfilePanelStudentPanelP(student, cardLayout, container);
        ChangePass = new ChangePasswordPanel_P(student, cardLayout, container);
        setTest= new setUpTest(student, cardLayout, container);
        TestHisView = new ViewTestHistoryPanelP(student, cardLayout, container);
        FAVQuesView = new ViewFavoriteQuestions(student, cardLayout, container);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        StudentMenu = new javax.swing.JLabel();
        UpdateProflie = new javax.swing.JButton();
        ViewProflie = new javax.swing.JButton();
        ChangePassword = new javax.swing.JButton();
        DeleteAccount = new javax.swing.JButton();
        TakeTest = new javax.swing.JButton();
        ViewTestHistory = new javax.swing.JButton();
        ViewFavoriteQuestions = new javax.swing.JButton();

        jButton10.setBackground(new java.awt.Color(74, 25, 72));
        jButton10.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jButton10.setForeground(new java.awt.Color(244, 242, 226));
        jButton10.setText("Login");
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.setFocusPainted(false);
        jButton10.setPreferredSize(new java.awt.Dimension(145, 60));
        jButton10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton10MouseMoved(evt);
            }
        });
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton10MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton10MousePressed(evt);
            }
        });
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(74, 25, 72));
        jButton12.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jButton12.setForeground(new java.awt.Color(244, 242, 226));
        jButton12.setText("Login");
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.setFocusPainted(false);
        jButton12.setPreferredSize(new java.awt.Dimension(145, 60));
        jButton12.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton12MouseMoved(evt);
            }
        });
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton12MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton12MousePressed(evt);
            }
        });
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton16.setBackground(new java.awt.Color(74, 25, 72));
        jButton16.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jButton16.setForeground(new java.awt.Color(244, 242, 226));
        jButton16.setText("Login");
        jButton16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton16.setFocusPainted(false);
        jButton16.setPreferredSize(new java.awt.Dimension(145, 60));
        jButton16.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton16MouseMoved(evt);
            }
        });
        jButton16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton16MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton16MousePressed(evt);
            }
        });
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(244, 242, 226));
        setPreferredSize(new java.awt.Dimension(555, 474));
        setLayout(new java.awt.GridBagLayout());

        Logout.setBackground(new java.awt.Color(0, 0, 0));
        Logout.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 0, 0));
        Logout.setText("Logout");
        Logout.setBorderPainted(false);
        Logout.setFocusPainted(false);
        Logout.setFocusable(false);
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 268;
        gridBagConstraints.ipady = -8;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 16);
        add(Logout, gridBagConstraints);

        StudentMenu.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        StudentMenu.setForeground(new java.awt.Color(0, 0, 0));
        StudentMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StudentMenu.setText("Student Menu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 315;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        add(StudentMenu, gridBagConstraints);

        UpdateProflie.setBackground(new java.awt.Color(74, 25, 72));
        UpdateProflie.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        UpdateProflie.setForeground(new java.awt.Color(244, 242, 226));
        UpdateProflie.setText("Update Proflie");
        UpdateProflie.setBorderPainted(false);
        UpdateProflie.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UpdateProflie.setFocusPainted(false);
        UpdateProflie.setFocusable(false);
        UpdateProflie.setPreferredSize(new java.awt.Dimension(145, 60));
        UpdateProflie.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                UpdateProflieMouseMoved(evt);
            }
        });
        UpdateProflie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UpdateProflieMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UpdateProflieMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UpdateProflieMousePressed(evt);
            }
        });
        UpdateProflie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateProflieActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 250;
        gridBagConstraints.ipady = -25;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(UpdateProflie, gridBagConstraints);

        ViewProflie.setBackground(new java.awt.Color(74, 25, 72));
        ViewProflie.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        ViewProflie.setForeground(new java.awt.Color(244, 242, 226));
        ViewProflie.setText("View Proflie");
        ViewProflie.setBorderPainted(false);
        ViewProflie.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewProflie.setFocusPainted(false);
        ViewProflie.setFocusable(false);
        ViewProflie.setPreferredSize(new java.awt.Dimension(145, 60));
        ViewProflie.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ViewProflieMouseMoved(evt);
            }
        });
        ViewProflie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ViewProflieMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ViewProflieMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ViewProflieMousePressed(evt);
            }
        });
        ViewProflie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewProflieActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 250;
        gridBagConstraints.ipady = -25;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(ViewProflie, gridBagConstraints);

        ChangePassword.setBackground(new java.awt.Color(74, 25, 72));
        ChangePassword.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        ChangePassword.setForeground(new java.awt.Color(244, 242, 226));
        ChangePassword.setText("Change Password");
        ChangePassword.setBorderPainted(false);
        ChangePassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ChangePassword.setFocusPainted(false);
        ChangePassword.setFocusable(false);
        ChangePassword.setPreferredSize(new java.awt.Dimension(145, 60));
        ChangePassword.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ChangePasswordMouseMoved(evt);
            }
        });
        ChangePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ChangePasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ChangePasswordMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ChangePasswordMousePressed(evt);
            }
        });
        ChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePasswordActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 250;
        gridBagConstraints.ipady = -25;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(ChangePassword, gridBagConstraints);

        DeleteAccount.setBackground(new java.awt.Color(74, 25, 72));
        DeleteAccount.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        DeleteAccount.setForeground(new java.awt.Color(244, 242, 226));
        DeleteAccount.setText("Delete Account");
        DeleteAccount.setBorderPainted(false);
        DeleteAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeleteAccount.setFocusPainted(false);
        DeleteAccount.setFocusable(false);
        DeleteAccount.setPreferredSize(new java.awt.Dimension(145, 60));
        DeleteAccount.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                DeleteAccountMouseMoved(evt);
            }
        });
        DeleteAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DeleteAccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DeleteAccountMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DeleteAccountMousePressed(evt);
            }
        });
        DeleteAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteAccountActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 250;
        gridBagConstraints.ipady = -25;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(DeleteAccount, gridBagConstraints);

        TakeTest.setBackground(new java.awt.Color(74, 25, 72));
        TakeTest.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        TakeTest.setForeground(new java.awt.Color(244, 242, 226));
        TakeTest.setText("Take Test");
        TakeTest.setBorderPainted(false);
        TakeTest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TakeTest.setFocusPainted(false);
        TakeTest.setFocusable(false);
        TakeTest.setPreferredSize(new java.awt.Dimension(145, 60));
        TakeTest.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                TakeTestMouseMoved(evt);
            }
        });
        TakeTest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TakeTestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TakeTestMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TakeTestMousePressed(evt);
            }
        });
        TakeTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TakeTestActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 250;
        gridBagConstraints.ipady = -25;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(TakeTest, gridBagConstraints);

        ViewTestHistory.setBackground(new java.awt.Color(74, 25, 72));
        ViewTestHistory.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        ViewTestHistory.setForeground(new java.awt.Color(244, 242, 226));
        ViewTestHistory.setText("View Test History");
        ViewTestHistory.setBorderPainted(false);
        ViewTestHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewTestHistory.setFocusPainted(false);
        ViewTestHistory.setFocusable(false);
        ViewTestHistory.setPreferredSize(new java.awt.Dimension(145, 60));
        ViewTestHistory.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ViewTestHistoryMouseMoved(evt);
            }
        });
        ViewTestHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ViewTestHistoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ViewTestHistoryMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ViewTestHistoryMousePressed(evt);
            }
        });
        ViewTestHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewTestHistoryActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 250;
        gridBagConstraints.ipady = -25;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(ViewTestHistory, gridBagConstraints);

        ViewFavoriteQuestions.setBackground(new java.awt.Color(74, 25, 72));
        ViewFavoriteQuestions.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        ViewFavoriteQuestions.setForeground(new java.awt.Color(244, 242, 226));
        ViewFavoriteQuestions.setText("View Favorite Questions");
        ViewFavoriteQuestions.setBorderPainted(false);
        ViewFavoriteQuestions.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewFavoriteQuestions.setFocusPainted(false);
        ViewFavoriteQuestions.setFocusable(false);
        ViewFavoriteQuestions.setPreferredSize(new java.awt.Dimension(145, 60));
        ViewFavoriteQuestions.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ViewFavoriteQuestionsMouseMoved(evt);
            }
        });
        ViewFavoriteQuestions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ViewFavoriteQuestionsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ViewFavoriteQuestionsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ViewFavoriteQuestionsMousePressed(evt);
            }
        });
        ViewFavoriteQuestions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewFavoriteQuestionsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 250;
        gridBagConstraints.ipady = -25;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(ViewFavoriteQuestions, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        // TODO add your handling code here:
        container.remove(VStudent);
        container.remove(ChangePass);
        container.remove(UpdateStudentProf);
        container.remove(setTest);
        container.remove(FAVQuesView); 
        container.remove(TestHisView);
        container.revalidate();
        container.repaint();
        VStudent = null ;
        ChangePass = null ;
        UpdateStudentProf = null ;
        setTest = null ;
        FAVQuesView = null ;
        TestHisView = null ;
        student = new Student() ;
        System.gc();
        cardLayout.show(container, "Welcome");
    }//GEN-LAST:event_LogoutMouseClicked

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutActionPerformed

    private void UpdateProflieMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateProflieMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateProflieMouseMoved

    private void UpdateProflieMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateProflieMouseEntered
        // TODO add your handling code here:
        UpdateProflie.setBackground(Color.decode("#F4F2E2"));
        UpdateProflie.setBorder(BorderFactory.createLineBorder(Color.BLACK, 5, true));
        UpdateProflie.setBorderPainted(true);
        UpdateProflie.setForeground(Color.BLACK);
    }//GEN-LAST:event_UpdateProflieMouseEntered

    private void UpdateProflieMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateProflieMouseExited
        // TODO add your handling code here:
        UpdateProflie.setBackground(Color.decode("#4A1948"));
        UpdateProflie.setBorderPainted(false);
        UpdateProflie.setForeground(Color.decode("#F4F2E2"));
    }//GEN-LAST:event_UpdateProflieMouseExited

    private void UpdateProflieMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateProflieMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateProflieMousePressed

    private void UpdateProflieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateProflieActionPerformed
        // TODO add your handling code here:
        
        container.add(UpdateStudentProf, "StudentUpdateprof");
        cardLayout.show(container, "StudentUpdateprof");
    }//GEN-LAST:event_UpdateProflieActionPerformed

    private void ViewProflieMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewProflieMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewProflieMouseMoved

    private void ViewProflieMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewProflieMouseEntered
        // TODO add your handling code here:
        ViewProflie.setBackground(Color.decode("#F4F2E2"));
        ViewProflie.setBorder(BorderFactory.createLineBorder(Color.BLACK, 5, true));
        ViewProflie.setBorderPainted(true);
        ViewProflie.setForeground(Color.BLACK);
    }//GEN-LAST:event_ViewProflieMouseEntered

    private void ViewProflieMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewProflieMouseExited
        // TODO add your handling code here:
        ViewProflie.setBackground(Color.decode("#4A1948"));
        ViewProflie.setBorderPainted(false);
        ViewProflie.setForeground(Color.decode("#F4F2E2"));
    }//GEN-LAST:event_ViewProflieMouseExited

    private void ViewProflieMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewProflieMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewProflieMousePressed

    private void ViewProflieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewProflieActionPerformed
        // TODO add your handling code here:
        
        container.add(VStudent, "StudentViewProf"); 
        cardLayout.show(container, "StudentViewProf");
    }//GEN-LAST:event_ViewProflieActionPerformed

    private void jButton10MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10MouseMoved

    private void jButton10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10MouseEntered

    private void jButton10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10MouseExited

    private void jButton10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10MousePressed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void ChangePasswordMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePasswordMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_ChangePasswordMouseMoved

    private void ChangePasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePasswordMouseEntered
        // TODO add your handling code here:
        ChangePassword.setBackground(Color.decode("#F4F2E2"));
        ChangePassword.setBorder(BorderFactory.createLineBorder(Color.BLACK, 5, true));
        ChangePassword.setBorderPainted(true);
        ChangePassword.setForeground(Color.BLACK);
    }//GEN-LAST:event_ChangePasswordMouseEntered

    private void ChangePasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePasswordMouseExited
        // TODO add your handling code here:
        ChangePassword.setBackground(Color.decode("#4A1948"));
        ChangePassword.setBorderPainted(false);
        ChangePassword.setForeground(Color.decode("#F4F2E2"));
    }//GEN-LAST:event_ChangePasswordMouseExited

    private void ChangePasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePasswordMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChangePasswordMousePressed

    private void ChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePasswordActionPerformed
        // TODO add your handling code here:
        
        container.add(ChangePass, "StudentChangePass"); 
        cardLayout.show(container, "StudentChangePass");
    }//GEN-LAST:event_ChangePasswordActionPerformed

    private void jButton12MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12MouseMoved

    private void jButton12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12MouseEntered

    private void jButton12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12MouseExited

    private void jButton12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12MousePressed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void DeleteAccountMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteAccountMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteAccountMouseMoved

    private void DeleteAccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteAccountMouseEntered
        // TODO add your handling code here:
        DeleteAccount.setBackground(Color.decode("#F4F2E2"));
        DeleteAccount.setBorder(BorderFactory.createLineBorder(Color.BLACK, 5, true));
        DeleteAccount.setBorderPainted(true);
        DeleteAccount.setForeground(Color.BLACK);
    }//GEN-LAST:event_DeleteAccountMouseEntered

    private void DeleteAccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteAccountMouseExited
        // TODO add your handling code here:
        DeleteAccount.setBackground(Color.decode("#4A1948"));
        DeleteAccount.setBorderPainted(false);
        DeleteAccount.setForeground(Color.decode("#F4F2E2"));
    }//GEN-LAST:event_DeleteAccountMouseExited

    private void DeleteAccountMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteAccountMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteAccountMousePressed

    private void DeleteAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteAccountActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(
                null,                             // Parent component (null for center of screen)
                "Are you sure to delete the the account?",        // Message
                "Delete Account alert",                   // Title
                JOptionPane.YES_NO_OPTION,        // Options
                JOptionPane.QUESTION_MESSAGE      // Icon type
        );
        if (response == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(
                    null,
                    "The Account Deleted!",
                    "Delete The Account",
                    JOptionPane.INFORMATION_MESSAGE
            );
            student.removeAccount() ;
            LogoutMouseClicked();
        } else {
            JOptionPane.showMessageDialog(
                    null,
                    "Delete is disabled",
                    "disable the Deletion",
                    JOptionPane.INFORMATION_MESSAGE
            );
        }
    }//GEN-LAST:event_DeleteAccountActionPerformed

    private void TakeTestMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TakeTestMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TakeTestMouseMoved

    private void TakeTestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TakeTestMouseEntered
        // TODO add your handling code here:
        TakeTest.setBackground(Color.decode("#F4F2E2"));
        TakeTest.setBorder(BorderFactory.createLineBorder(Color.BLACK, 5, true));
        TakeTest.setBorderPainted(true);
        TakeTest.setForeground(Color.BLACK);
    }//GEN-LAST:event_TakeTestMouseEntered

    private void TakeTestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TakeTestMouseExited
        // TODO add your handling code here:
        TakeTest.setBackground(Color.decode("#4A1948"));
        TakeTest.setBorderPainted(false);
        TakeTest.setForeground(Color.decode("#F4F2E2"));
    }//GEN-LAST:event_TakeTestMouseExited

    private void TakeTestMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TakeTestMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TakeTestMousePressed

    private void TakeTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TakeTestActionPerformed
        // TODO add your handling code here:
         
        container.add(setTest, "setTest");
        cardLayout.show(container, "setTest");// waiting Take Test
    }//GEN-LAST:event_TakeTestActionPerformed

    private void ViewTestHistoryMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewTestHistoryMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewTestHistoryMouseMoved

    private void ViewTestHistoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewTestHistoryMouseEntered
        // TODO add your handling code here:
        ViewTestHistory.setBackground(Color.decode("#F4F2E2"));
        ViewTestHistory.setBorder(BorderFactory.createLineBorder(Color.BLACK, 5, true));
        ViewTestHistory.setBorderPainted(true);
        ViewTestHistory.setForeground(Color.BLACK);
    }//GEN-LAST:event_ViewTestHistoryMouseEntered

    private void ViewTestHistoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewTestHistoryMouseExited
        // TODO add your handling code here:
        ViewTestHistory.setBackground(Color.decode("#4A1948"));
        ViewTestHistory.setBorderPainted(false);
        ViewTestHistory.setForeground(Color.decode("#F4F2E2"));
    }//GEN-LAST:event_ViewTestHistoryMouseExited

    private void ViewTestHistoryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewTestHistoryMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewTestHistoryMousePressed

    private void ViewTestHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewTestHistoryActionPerformed
        // TODO add your handling code here:
        
        container.add(TestHisView, "TestHView");
        cardLayout.show(container, "TestHView");
    }//GEN-LAST:event_ViewTestHistoryActionPerformed

    private void jButton16MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton16MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16MouseMoved

    private void jButton16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton16MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16MouseEntered

    private void jButton16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton16MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16MouseExited

    private void jButton16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton16MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16MousePressed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void ViewFavoriteQuestionsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewFavoriteQuestionsMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewFavoriteQuestionsMouseMoved

    private void ViewFavoriteQuestionsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewFavoriteQuestionsMouseEntered
        // TODO add your handling code here:
        ViewFavoriteQuestions.setBackground(Color.decode("#F4F2E2"));
        ViewFavoriteQuestions.setBorder(BorderFactory.createLineBorder(Color.BLACK, 5, true));
        ViewFavoriteQuestions.setBorderPainted(true);
        ViewFavoriteQuestions.setForeground(Color.BLACK);
    }//GEN-LAST:event_ViewFavoriteQuestionsMouseEntered

    private void ViewFavoriteQuestionsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewFavoriteQuestionsMouseExited
        // TODO add your handling code here:
        ViewFavoriteQuestions.setBackground(Color.decode("#4A1948"));
        ViewFavoriteQuestions.setBorderPainted(false);
        ViewFavoriteQuestions.setForeground(Color.decode("#F4F2E2"));
    }//GEN-LAST:event_ViewFavoriteQuestionsMouseExited

    private void ViewFavoriteQuestionsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewFavoriteQuestionsMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewFavoriteQuestionsMousePressed

    private void ViewFavoriteQuestionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewFavoriteQuestionsActionPerformed
        // TODO add your handling code here:
        
        container.add(FAVQuesView, "FAVQView");
        cardLayout.show(container, "FAVQView");
    }//GEN-LAST:event_ViewFavoriteQuestionsActionPerformed
    private void LogoutMouseClicked() {
        container.remove(VStudent);
        container.remove(ChangePass);
        container.remove(UpdateStudentProf);
        container.remove(UpdateStudentProf); 
        //container.remove(FAVQuesView); 
        container.remove(TestHisView);
        container.revalidate();
        container.repaint();
        VStudent = null ;
        ChangePass = null ;
        UpdateStudentProf = null ;
        TakeTest = null ;
        //FAVQuesView = null ;
        TestHisView = null ;
        student = new Student() ;
        System.gc();
        cardLayout.show(container, "Welcome");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChangePassword;
    private javax.swing.JButton DeleteAccount;
    private javax.swing.JButton Logout;
    private javax.swing.JLabel StudentMenu;
    private javax.swing.JButton TakeTest;
    private javax.swing.JButton UpdateProflie;
    private javax.swing.JButton ViewFavoriteQuestions;
    private javax.swing.JButton ViewProflie;
    private javax.swing.JButton ViewTestHistory;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton16;
    // End of variables declaration//GEN-END:variables

    
}
