/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.StudentPanels;

import EndUser.Student;
import TestSystem.Test;
import java.awt.CardLayout;
import java.awt.Color;
import java.net.URL;
import javax.swing.BorderFactory;
import javax.swing.JPanel;

/**
 *
 * @author Zeyad
 */
public class ViewProfilePanelStudentPanelP extends javax.swing.JPanel {

    private Student student;
    private CardLayout cardLayout;
    private JPanel container;

    /**
     * Creates new form ViewProfilePanelP
     * @param student
     * @param cardLayout
     * @param container
     */
    public ViewProfilePanelStudentPanelP(Student student, CardLayout cardLayout, JPanel container) {
        initComponents();
        this.student = student;
        this.cardLayout = cardLayout;
        this.container = container;
        UsernameHolder.setText(student.getUserName());
        EmailHolder.setText(student.getEmail());
        FnameHolder.setText(student.getFirstName());
        LnameHolder.setText(student.getLastName());
        AddressHolder.setText(student.getAddress());
        GradeHolder.setText(student.getGrade());
        InstituteHolder.setText(student.getInstitute());
        PassedTCountHolder.setText(String.valueOf(student.getPassedTestsCount()));
        TotalTOATestsHolder.setText(String.valueOf(student.getTotalTimeOfAllTests()));
        if (!(student.getTakenTests() == null)) {
            if (!(student.getTakenTests().isEmpty())) {
                StringBuilder resultBuilder = new StringBuilder("<html>");
                for (Test test : student.getTakenTests()) {
                    resultBuilder.append("- ")
                     .append(test.toString())
                     .append("<br>")  ;   
                }
                resultBuilder.append("</html>");
                TakenTestsHolder.setText(resultBuilder.toString());
            } else {
                TakenTestsHolder.setText("This student has not taken any exam yet.");
            }

        } else TakenTestsHolder.setText("This student has not taken any exam yet.");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        FirstName = new javax.swing.JLabel();
        LastName = new javax.swing.JLabel();
        Grade = new javax.swing.JLabel();
        Institute = new javax.swing.JLabel();
        PassedTCount = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        StudentProfile = new javax.swing.JLabel();
        UsernameHolder = new javax.swing.JLabel();
        EmailHolder = new javax.swing.JLabel();
        LnameHolder = new javax.swing.JLabel();
        FnameHolder = new javax.swing.JLabel();
        AddressHolder = new javax.swing.JLabel();
        GradeHolder = new javax.swing.JLabel();
        InstituteHolder = new javax.swing.JLabel();
        PassedTCountHolder = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        TotalTOATests = new javax.swing.JLabel();
        TakenTests = new javax.swing.JLabel();
        TotalTOATestsHolder = new javax.swing.JLabel();
        TakenTestsHolder = new javax.swing.JLabel();

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Consolas", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(1, 1, 1));
        jLabel3.setText("jLabel1");
        jLabel3.setOpaque(true);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Consolas", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(1, 1, 1));
        jLabel4.setText("jLabel1");
        jLabel4.setOpaque(true);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Consolas", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(1, 1, 1));
        jLabel5.setText("jLabel1");
        jLabel5.setOpaque(true);

        setBackground(new java.awt.Color(244, 242, 226));
        setForeground(new java.awt.Color(74, 25, 72));
        setAutoscrolls(true);
        setLayout(new java.awt.GridBagLayout());

        Username.setBackground(new java.awt.Color(74, 25, 72));
        Username.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        Username.setForeground(new java.awt.Color(0, 0, 0));
        Username.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Username.setText("Username:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 137;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(Username, gridBagConstraints);

        Email.setBackground(new java.awt.Color(74, 25, 72));
        Email.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        Email.setForeground(new java.awt.Color(0, 0, 0));
        Email.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Email.setText("Email:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(Email, gridBagConstraints);

        FirstName.setBackground(new java.awt.Color(74, 25, 72));
        FirstName.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        FirstName.setForeground(new java.awt.Color(0, 0, 0));
        FirstName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        FirstName.setText("First Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 49;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(FirstName, gridBagConstraints);

        LastName.setBackground(new java.awt.Color(74, 25, 72));
        LastName.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        LastName.setForeground(new java.awt.Color(0, 0, 0));
        LastName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LastName.setText("Last Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 85;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(LastName, gridBagConstraints);

        Grade.setBackground(new java.awt.Color(74, 25, 72));
        Grade.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        Grade.setForeground(new java.awt.Color(0, 0, 0));
        Grade.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Grade.setText("Grade:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 123;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(Grade, gridBagConstraints);

        Institute.setBackground(new java.awt.Color(74, 25, 72));
        Institute.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        Institute.setForeground(new java.awt.Color(0, 0, 0));
        Institute.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Institute.setText("Institute:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 164;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(Institute, gridBagConstraints);

        PassedTCount.setBackground(new java.awt.Color(74, 25, 72));
        PassedTCount.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        PassedTCount.setForeground(new java.awt.Color(0, 0, 0));
        PassedTCount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PassedTCount.setText("Passed Tests Count:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 85;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(PassedTCount, gridBagConstraints);

        Address.setBackground(new java.awt.Color(74, 25, 72));
        Address.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        Address.setForeground(new java.awt.Color(0, 0, 0));
        Address.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Address.setText("Address:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 69;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(Address, gridBagConstraints);

        StudentProfile.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        StudentProfile.setForeground(new java.awt.Color(0, 0, 0));
        StudentProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StudentProfile.setText("Student Profile");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 370;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(StudentProfile, gridBagConstraints);

        UsernameHolder.setBackground(new java.awt.Color(255, 255, 255));
        UsernameHolder.setFont(new java.awt.Font("Consolas", 0, 20)); // NOI18N
        UsernameHolder.setForeground(new java.awt.Color(1, 1, 1));
        UsernameHolder.setText("\"HOLDER\"");
        UsernameHolder.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 191;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(UsernameHolder, gridBagConstraints);

        EmailHolder.setBackground(new java.awt.Color(255, 255, 255));
        EmailHolder.setFont(new java.awt.Font("Consolas", 0, 20)); // NOI18N
        EmailHolder.setForeground(new java.awt.Color(1, 1, 1));
        EmailHolder.setText("\"HOLDER\"");
        EmailHolder.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 191;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(EmailHolder, gridBagConstraints);

        LnameHolder.setBackground(new java.awt.Color(255, 255, 255));
        LnameHolder.setFont(new java.awt.Font("Consolas", 0, 20)); // NOI18N
        LnameHolder.setForeground(new java.awt.Color(1, 1, 1));
        LnameHolder.setText("\"HOLDER\"");
        LnameHolder.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 191;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(LnameHolder, gridBagConstraints);

        FnameHolder.setBackground(new java.awt.Color(255, 255, 255));
        FnameHolder.setFont(new java.awt.Font("Consolas", 0, 20)); // NOI18N
        FnameHolder.setForeground(new java.awt.Color(1, 1, 1));
        FnameHolder.setText("\"HOLDER\"");
        FnameHolder.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 191;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(FnameHolder, gridBagConstraints);

        AddressHolder.setBackground(new java.awt.Color(255, 255, 255));
        AddressHolder.setFont(new java.awt.Font("Consolas", 0, 20)); // NOI18N
        AddressHolder.setForeground(new java.awt.Color(1, 1, 1));
        AddressHolder.setText("\"HOLDER\"");
        AddressHolder.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 191;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(AddressHolder, gridBagConstraints);

        GradeHolder.setBackground(new java.awt.Color(255, 255, 255));
        GradeHolder.setFont(new java.awt.Font("Consolas", 0, 20)); // NOI18N
        GradeHolder.setForeground(new java.awt.Color(1, 1, 1));
        GradeHolder.setText("\"HOLDER\"");
        GradeHolder.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 191;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(GradeHolder, gridBagConstraints);

        InstituteHolder.setBackground(new java.awt.Color(255, 255, 255));
        InstituteHolder.setFont(new java.awt.Font("Consolas", 0, 20)); // NOI18N
        InstituteHolder.setForeground(new java.awt.Color(1, 1, 1));
        InstituteHolder.setText("\"HOLDER\"");
        InstituteHolder.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 191;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(InstituteHolder, gridBagConstraints);

        PassedTCountHolder.setBackground(new java.awt.Color(255, 255, 255));
        PassedTCountHolder.setFont(new java.awt.Font("Consolas", 0, 20)); // NOI18N
        PassedTCountHolder.setForeground(new java.awt.Color(1, 1, 1));
        PassedTCountHolder.setText("\"HOLDER\"");
        PassedTCountHolder.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 191;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(PassedTCountHolder, gridBagConstraints);

        BackButton.setBackground(new java.awt.Color(74, 25, 72));
        BackButton.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        BackButton.setToolTipText("Click to go back");
        BackButton.setBorderPainted(false);
        BackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackButton.setFocusPainted(false);
        BackButton.setFocusable(false);
        BackButton.setMaximumSize(new java.awt.Dimension(145, 60));
        BackButton.setMinimumSize(new java.awt.Dimension(145, 60));
        BackButton.setPreferredSize(new java.awt.Dimension(145, 60));
        BackButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BackButtonFocusGained(evt);
            }
        });
        BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackButtonMouseExited(evt);
            }
        });
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(BackButton, gridBagConstraints);

        TotalTOATests.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        TotalTOATests.setForeground(new java.awt.Color(0, 0, 0));
        TotalTOATests.setText("Total Time Of All Tests:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(TotalTOATests, gridBagConstraints);

        TakenTests.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        TakenTests.setForeground(new java.awt.Color(0, 0, 0));
        TakenTests.setText("Taken Tests:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(TakenTests, gridBagConstraints);

        TotalTOATestsHolder.setBackground(new java.awt.Color(255, 255, 255));
        TotalTOATestsHolder.setFont(new java.awt.Font("Consolas", 0, 20)); // NOI18N
        TotalTOATestsHolder.setForeground(new java.awt.Color(0, 0, 0));
        TotalTOATestsHolder.setText("\"HOLDER\"");
        TotalTOATestsHolder.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 191;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(TotalTOATestsHolder, gridBagConstraints);

        TakenTestsHolder.setBackground(new java.awt.Color(255, 255, 255));
        TakenTestsHolder.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        TakenTestsHolder.setForeground(new java.awt.Color(0, 0, 0));
        TakenTestsHolder.setText("\"HOLDER\"");
        TakenTestsHolder.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        TakenTestsHolder.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 550;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(TakenTestsHolder, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BackButtonFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_BackButtonFocusGained

    private void BackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BackButtonMouseClicked

    private void BackButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseEntered
        // TODO add your handling code here:
        URL iconURL = getClass().getResource("/lib/turn-back.png");
        if (iconURL != null) {
            BackButton.setIcon(new javax.swing.ImageIcon(iconURL));
        } else {
            // Handle the error, e.g., log it or show a default icon
            System.err.println("Resource not found: /lib/turn-back.png");
        }
        BackButton.setBackground(Color.decode("#F4F2E2"));
        BackButton.setBorder(BorderFactory.createLineBorder(Color.BLACK, 5, true));
        BackButton.setBorderPainted(true);
    }//GEN-LAST:event_BackButtonMouseEntered

    private void BackButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseExited
        // TODO add your handling code here:
        URL iconURL = getClass().getResource("/lib/turnback-40.png");
        if (iconURL != null) {
            BackButton.setIcon(new javax.swing.ImageIcon(iconURL));
        } else {
            // Handle the error, e.g., log it or show a default icon
            System.err.println("Resource not found: /lib/turnback-40.png");
        }
        BackButton.setBackground(Color.decode("#4A1948"));
        BackButton.setBorderPainted(false);
        BackButton.setForeground(Color.decode("#F4F2E2"));

    }//GEN-LAST:event_BackButtonMouseExited

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        cardLayout.show(container, "StudentMenu");
    }//GEN-LAST:event_BackButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JLabel AddressHolder;
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel EmailHolder;
    private javax.swing.JLabel FirstName;
    private javax.swing.JLabel FnameHolder;
    private javax.swing.JLabel Grade;
    private javax.swing.JLabel GradeHolder;
    private javax.swing.JLabel Institute;
    private javax.swing.JLabel InstituteHolder;
    private javax.swing.JLabel LastName;
    private javax.swing.JLabel LnameHolder;
    private javax.swing.JLabel PassedTCount;
    private javax.swing.JLabel PassedTCountHolder;
    private javax.swing.JLabel StudentProfile;
    private javax.swing.JLabel TakenTests;
    private javax.swing.JLabel TakenTestsHolder;
    private javax.swing.JLabel TotalTOATests;
    private javax.swing.JLabel TotalTOATestsHolder;
    private javax.swing.JLabel Username;
    private javax.swing.JLabel UsernameHolder;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
