# This workflow will build a Java project with Ant
name: Java CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4    # This will include your lib folder with javax.mail.jar
    
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'oracle'
    
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml compile
