name: Java CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'oracle'
    
    # Change to your project directory
    - name: Change to project directory
      run: |
        ls -la  # Debug: list root contents
        cd TestGeneratorSystem
        ls -la  # Debug: list project contents
    
    - name: Build with Ant
      working-directory: ./TestGeneratorSystem
      run: ant -noinput -buildfile build.xml compile
